### PR TITLE
Initial setup and configuration

### PR DESCRIPTION
**Pull request by antonyk**
Configure and customize the scaffold into a starting state for our specific project.

PR includes changes to readme and config files, and additional dependencies.

### CODE REVIEW

**Review by nathan-saygers — APPROVED** [review]
Thanks @antonyk.  Looks good.

**Review by joshuabhorrocks — APPROVED** [review]
Readme is looking good, changes can be merged

**Review by tuskydev — COMMENTED** [review]
Nice additions, looking good.

**Review by tuskydev — APPROVED** [review]
Nice additions, looking good. v2

**Pull request merged**
