### PR TITLE
Login Design Updates

### PR DESCRIPTION
**Pull request by joshuabhorrocks**
Updated the design of the login page with the Eco-Soap Bank logo and welcome message, as well as added break points between different widths and heights that would visually break the page.

### CODE REVIEW

**Comment by nathan-saygers** [comment]
@joshuabhorrocks - Nice work.  Looks much more it's ours with the logo in there.

There are some screenwidths at which the widget overlaps the logo.  Mostly an issue on mobile, but it seems there's a tiny amount overlap on desktop views as well in the 600 - 900px height range

Mobile Example: 
Screen Shot 2020-08-12 at 11 00 45 AM

**Comment by joshuabhorrocks** [comment]
Okay, I'll add some breakpoints specifically targeting those ranges and then re-push it

**Review by tuskydev — APPROVED** [review]
I like how you considered media queries this early on well done

**Review by nathan-saygers — APPROVED** [review]
That solves it on desktop for me.  Looks good to go.

**Comment by antonyk** [comment]
Looks good to me. Well done!

**Review by antonyk — APPROVED** [review]
Looks good to me. Well done!

**Pull request merged**
