### PR TITLE
Brand config

### PR DESCRIPTION
**Pull request by antonyk**
Configured Okta with Client's branding
Styled Login
Updated Theme override

### CODE REVIEW

**Review by joshuabhorrocks — COMMENTED** [review]
The readme looks like the formatting got messed up with our names and stuff. Can you take a look to see if it still displays correctly and such? Otherwise everything else looks good.

**Review by nathan-saygers — COMMENTED** [review]
@antonyk Is the schema.graphql file just for reference?

**Review by joshuabhorrocks — APPROVED** [review]

**Comment by antonyk** [comment]
> @antonyk Is the schema.graphql file just for reference?

Yes, both that and the introspectionSchema.json file are both for reference purposes only.

**Comment by antonyk** [comment]
> The readme looks like the formatting got messed up with our names and stuff. Can you take a look to see if it still displays correctly and such? Otherwise everything else looks good.

Yeah, I tested it and after the formatting was auto-updated by prettier and it still seemed to look fine.

**Review by nathan-saygers — APPROVED** [review]

**Review by tuskydev — APPROVED** [review]
Good notes in between code.

**Pull request merged**
