### PR TITLE
Feature/side bar popup

### PR DESCRIPTION
**Pull request by tuskydev**
#### WIP: 
*  Look for an NPM that expands `mainImages` in Carousel when clicked
* Add dummy data to GraphQL to test out images/videos `(this is currently being hardcoded instead)`

###  Preview of feature:
image

### CODE REVIEW

**Review by nathan-saygers — APPROVED** [review]
This is great stuff @Diddleslip! Big feature push.  Awesome also to see you take to heart the feedback about making more commits.  This PR looks good. Only one comment:
- on line 27 of PopUpBar.js onHide() the function that affects the gray area when the modal is closed?  If this continues to give you issues let's meet as the whole team to try to tackle it.
Screen Shot 2020-09-18 at 9 25 25 AM

**Comment by tuskydev** [comment]
@nathan-saygers It's really satisfying adding commit messages 😅, and I'm fine with the functionality of the pop up as-is now, but if you have more functionality you'd like I'd be happy to meet with the team to add it

**Review by nathan-saygers — COMMENTED** [review]
Sounds good to me.  This is plenty for the purposes of presentation and such.

**Review by joshuabhorrocks — APPROVED** [review]
Looks like a masterpiece! This will really help tie it all together to looks super clean

**Pull request merged**
